package ptv_restaurant;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author ceo_emmanuel
 */
public class VentanaPadre extends javax.swing.JFrame {

    JDesktopPane escritorio;
    String nombreMesaOprimida;

    public VentanaPadre() {
        //Inicializamos la variable de escritorio
        escritorio = new JDesktopPane();
        //Inicializamos mesasOcupadas
        mesasOcupadas = new JInternalFrame[8];
        //Seteamos al escriotorio como un contenedor de paneles
        this.setContentPane(escritorio);

        //Forzamos a que se calcule el tamaño de todos los elementos
        this.pack();

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_lugares = new javax.swing.JPanel();
        btn_terraza = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_lobby = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn_terraza = new javax.swing.JPanel();
        btn_mesa1 = new javax.swing.JButton();
        btn_mesa2 = new javax.swing.JButton();
        btn_mesa3 = new javax.swing.JButton();
        btn_mesa4 = new javax.swing.JButton();
        btn_mesa5 = new javax.swing.JButton();
        btn_mesa6 = new javax.swing.JButton();
        btn_mesa7 = new javax.swing.JButton();
        btn_mesa8 = new javax.swing.JButton();
        btn_barra = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menNuevaOrden = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pn_lugares.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btn_terraza.setBackground(new java.awt.Color(239, 237, 237));

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 56, 56));
        jLabel3.setText("Terraza");

        javax.swing.GroupLayout btn_terrazaLayout = new javax.swing.GroupLayout(btn_terraza);
        btn_terraza.setLayout(btn_terrazaLayout);
        btn_terrazaLayout.setHorizontalGroup(
            btn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(btn_terrazaLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(207, 207, 207))
        );
        btn_terrazaLayout.setVerticalGroup(
            btn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_terrazaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_lobby.setBackground(new java.awt.Color(110, 200, 155));

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lobby");

        javax.swing.GroupLayout btn_lobbyLayout = new javax.swing.GroupLayout(btn_lobby);
        btn_lobby.setLayout(btn_lobbyLayout);
        btn_lobbyLayout.setHorizontalGroup(
            btn_lobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_lobbyLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(239, 239, 239))
        );
        btn_lobbyLayout.setVerticalGroup(
            btn_lobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_lobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout pn_lugaresLayout = new javax.swing.GroupLayout(pn_lugares);
        pn_lugares.setLayout(pn_lugaresLayout);
        pn_lugaresLayout.setHorizontalGroup(
            pn_lugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lugaresLayout.createSequentialGroup()
                .addComponent(btn_lobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_terraza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_lugaresLayout.setVerticalGroup(
            pn_lugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_lobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_terraza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_terraza.setBackground(new java.awt.Color(230, 230, 230));
        pn_terraza.setBorder(null);

        btn_mesa1.setBackground(new java.awt.Color(53, 211, 116));
        btn_mesa1.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa1.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa1.setText("T1");
        btn_mesa1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa1.setBorderPainted(false);
        btn_mesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa2.setBackground(btn_mesa1.getBackground());
        btn_mesa2.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa2.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa2.setText("T2");
        btn_mesa2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa2.setBorderPainted(false);
        btn_mesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa3.setBackground(btn_mesa1.getBackground());
        btn_mesa3.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa3.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa3.setText("T3");
        btn_mesa3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa3.setBorderPainted(false);
        btn_mesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa4.setBackground(new java.awt.Color(222, 67, 78));
        btn_mesa4.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa4.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa4.setText("T4");
        btn_mesa4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa4.setBorderPainted(false);
        btn_mesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa5.setBackground(new java.awt.Color(108, 109, 236));
        btn_mesa5.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa5.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa5.setText("T5");
        btn_mesa5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa5.setBorderPainted(false);
        btn_mesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa6.setBackground(btn_mesa1.getBackground());
        btn_mesa6.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa6.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa6.setText("T6");
        btn_mesa6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa6.setBorderPainted(false);
        btn_mesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa7.setBackground(btn_mesa1.getBackground());
        btn_mesa7.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa7.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa7.setText("T7");
        btn_mesa7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa7.setBorderPainted(false);
        btn_mesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_mesa8.setBackground(btn_mesa1.getBackground());
        btn_mesa8.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_mesa8.setForeground(new java.awt.Color(253, 251, 251));
        btn_mesa8.setText("T8");
        btn_mesa8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_mesa8.setBorderPainted(false);
        btn_mesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentana(evt);
            }
        });

        btn_barra.setBackground(new java.awt.Color(235, 191, 109));
        btn_barra.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        btn_barra.setForeground(new java.awt.Color(253, 251, 251));
        btn_barra.setText("B A R R A");
        btn_barra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_barra.setBorderPainted(false);

        btn_regresar.setText("Regresar");

        javax.swing.GroupLayout pn_terrazaLayout = new javax.swing.GroupLayout(pn_terraza);
        pn_terraza.setLayout(pn_terrazaLayout);
        pn_terrazaLayout.setHorizontalGroup(
            pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_terrazaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_mesa2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(btn_mesa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mesa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(188, 188, 188)
                .addGroup(pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_mesa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mesa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209)
                .addGroup(pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mesa7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mesa8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mesa6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
            .addGroup(pn_terrazaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar)
                .addGap(81, 81, 81)
                .addComponent(btn_barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(164, 164, 164))
        );
        pn_terrazaLayout.setVerticalGroup(
            pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_terrazaLayout.createSequentialGroup()
                .addGroup(pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_terrazaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_regresar))
                .addGroup(pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_terrazaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pn_terrazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pn_terrazaLayout.createSequentialGroup()
                                .addComponent(btn_mesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btn_mesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_mesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_terrazaLayout.createSequentialGroup()
                                .addComponent(btn_mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btn_mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btn_mesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_terrazaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn_mesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );

        jMenu1.setText("Tools");

        menNuevaOrden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menNuevaOrden.setText("Nueva Orden");
        jMenu1.add(menNuevaOrden);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Cerrar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guardar");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ver");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem1.setText("pantalla completa");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("About");

        jMenuItem4.setText("Sobre papayon's");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_lugares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_terraza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_terraza, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JInternalFrame mesasOcupadas[];

    private void nuevaVentana(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaVentana

        int j = 0;
        //Se iconifican todas las ventanas abiertas
        for (JInternalFrame i : escritorio.getAllFrames()) {
            try {
                i.setIcon(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(VentanaPadre.class.getName()).log(Level.SEVERE, null, ex);
            }
            mesasOcupadas[j] = i;
        }
        //Comprobamos si existe mesa
        boolean existe = existeMesa();
        if (!existe) {
            //Se agrega nueva ventana hija
            JInternalFrame vHija
                    = new JInternalFrame("orden de trabajo", true, true, true, true);

            //Se crea el panel interno
            PanelHijo hijo = new PanelHijo(pn_terraza);
            // Se agregan propiedades de la ventana hijo
            vHija.add(hijo);
            vHija.pack();
            vHija.setLocation(100, 100);
            vHija.setVisible(true);
            //Se recupera el texto de botón para ponerlo al titulo de la ventana hija
            String nombreMesa = ((JButton) evt.getSource()).getText();
            vHija.setTitle(nombreMesa);
            //Agregamos la ventana hija al escritorio

            escritorio.add(vHija);
            pn_terraza.setVisible(false);
        }
    }//GEN-LAST:event_nuevaVentana
    private boolean existeMesa() {
        //Para iterar la lista te ventanas
        int j = 0;
        for (JInternalFrame i : escritorio.getAllFrames()) {
            //Checamos el titulo de cada internalFrame
            if (i.getTitle().equalsIgnoreCase(mesasOcupadas[j].getTitle())) {
                try {
                    mesasOcupadas[j].setIcon(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(VentanaPadre.class.getName()).log(Level.SEVERE, null, ex);
                }
                return true;
            }
            j++;
        }
        return false;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barra;
    private javax.swing.JPanel btn_lobby;
    private javax.swing.JButton btn_mesa1;
    private javax.swing.JButton btn_mesa2;
    private javax.swing.JButton btn_mesa3;
    private javax.swing.JButton btn_mesa4;
    private javax.swing.JButton btn_mesa5;
    private javax.swing.JButton btn_mesa6;
    private javax.swing.JButton btn_mesa7;
    private javax.swing.JButton btn_mesa8;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPanel btn_terraza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menNuevaOrden;
    private javax.swing.JPanel pn_lugares;
    private javax.swing.JPanel pn_terraza;
    // End of variables declaration//GEN-END:variables

}
