/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import DAO_Y_VO.ClienteDAO;
import DAO_Y_VO.ClienteVO;
import DAO_Y_VO.NotaVentaDAO;
import DAO_Y_VO.Nota_Detalles;
import DAO_Y_VO.Nota_VentaVO;
import java.util.ArrayList;
import javax.swing.JInternalFrame;

/**
 *
 * @author ceo_emmanuel
 */
public class Modificar_Nota extends javax.swing.JPanel {

    private final JInternalFrame frame;

    /**
     * Creates new form Modificar_Nota
     */
    public Modificar_Nota(JInternalFrame frame) {
        initComponents();
        this.frame = frame;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_detalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_folio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_mesa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_mesero = new javax.swing.JLabel();
        btn_ir = new javax.swing.JButton();
        lbl_fecha = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        btn_modificarCliente = new javax.swing.JButton();
        cbx_seleccionCliente = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        tb_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "sku", "nombre", "cantidad", "precio unitario"
            }
        ));
        tb_detalle.setEnabled(false);
        jScrollPane1.setViewportView(tb_detalle);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel5.setText("Total:");

        lbl_total.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(155, 255, 0));
        lbl_total.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Folio:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel2.add(tf_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, -1));

        jLabel2.setText("Fecha:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, -1));

        jLabel3.setText("Hora:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel4.setText("Mesa:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        lbl_mesa.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbl_mesa.setText("-");
        jPanel2.add(lbl_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 40, 40));

        jLabel6.setText("Cliente:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel8.setText("Atendió:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lbl_mesero.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbl_mesero.setText("-");
        jPanel2.add(lbl_mesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, 30));

        btn_ir.setText("Ir");
        btn_ir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_irActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, -1));

        lbl_fecha.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_fecha.setText("-");
        jPanel2.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 30));

        lbl_hora.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_hora.setText("-");
        jPanel2.add(lbl_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 30));

        btn_modificarCliente.setText("Modificar Cliente");
        btn_modificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jPanel2.add(cbx_seleccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int seleccionado;
    private void btn_irActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_irActionPerformed

        NotaVentaDAO ndao = new NotaVentaDAO(new Conector.Conector().conectarMySQL());

        int folio = Integer.parseInt(tf_folio.getText());
        Nota_VentaVO nota = ndao.getNota_ByID(folio);

        lbl_fecha.setText(nota.getFecha());
        lbl_hora.setText(nota.getHora());
        lbl_mesa.setText(String.valueOf(nota.getMesa()));
        
        lbl_mesero.setText(String.valueOf(nota.getMesero_idmesero()));

        ArrayList<Nota_Detalles> detalle = ndao.consultaDetallesDeNota(folio);

        int r = 0;
        double total = 0;
        for (Nota_Detalles d : detalle) {
            tb_detalle.setValueAt(d.getSku(), r, 0);
            tb_detalle.setValueAt(d.getNombre(), r, 1);
            tb_detalle.setValueAt(d.getCantidad(), r, 2);
            tb_detalle.setValueAt(d.getPrecioUnitario(), r, 3);
            total += d.getPrecioUnitario();

            r++;
        }

        lbl_total.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_irActionPerformed

    private void btn_modificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarClienteActionPerformed

        llenarCbx_clientes();
        
        
    }//GEN-LAST:event_btn_modificarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ir;
    private javax.swing.JButton btn_modificarCliente;
    private javax.swing.JComboBox<String> cbx_seleccionCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_mesa;
    private javax.swing.JLabel lbl_mesero;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tb_detalle;
    private javax.swing.JTextField tf_folio;
    // End of variables declaration//GEN-END:variables

    private void llenarCbx_clientes() {

        ArrayList<ClienteVO> lista_clientes = new ClienteDAO(new Conector.Conector().conectarMySQL()).consultaMasiva();

        for (ClienteVO cl : lista_clientes) {
            cbx_seleccionCliente.addItem(cl.getNombre_cliente());
        }

    }

}
