/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Conector.Conector;
import DAO_Y_VO.ClienteDAO;
import DAO_Y_VO.ClienteVO;
import DAO_Y_VO.NotaVentaDAO;
import DAO_Y_VO.Nota_VentaVO;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.arrays.ArrayLikeIterator;

/**
 *
 * @author ceo_emmanuel
 */
public class Pasarela_Pago extends javax.swing.JPanel {

    /**
     * Creates new form Pasarela_Pago
     */
    JDesktopPane escritorio;

    public Pasarela_Pago(String total, JDesktopPane escritorio) {
        this.escritorio = escritorio;
        initComponents();
        llenarCBX();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_efectivo = new javax.swing.JButton();
        btn_bitCoin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_ingreso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_cambio = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbx_clientes = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_efectivo.setBackground(new java.awt.Color(4, 205, 1));
        btn_efectivo.setForeground(new java.awt.Color(152, 152, 152));
        btn_efectivo.setText("Efectivo");
        add(btn_efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 60));

        btn_bitCoin.setBackground(new java.awt.Color(255, 215, 0));
        btn_bitCoin.setForeground(new java.awt.Color(152, 152, 152));
        btn_bitCoin.setText("BTC");
        add(btn_bitCoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 170, 60));

        jLabel4.setText("Total:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        lb_total.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lb_total.setText("0.00");
        add(lb_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 74, 34));

        jLabel1.setText("Efectivo:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 162, -1, -1));

        tf_ingreso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tf_ingresoPropertyChange(evt);
            }
        });
        add(tf_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 156, 160, -1));

        jLabel2.setText("Cambio");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        lbl_cambio.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbl_cambio.setText("0.00");
        add(lbl_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 52, 35));

        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ParaPos/pagar.png"))); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 114, 123));

        jLabel3.setText("Seleccione Cliente:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, -1));

        add(cbx_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        Conector con = new Conector();

        NotaVentaDAO cl = new NotaVentaDAO(con.conectarMySQL());
        Nota_VentaVO nota = new Nota_VentaVO();

        if (Integer.parseInt(lbl_cambio.getText()) >= 0.0) {

            //Registra pago en BD
        }
        JOptionPane.showMessageDialog(null, "EPA! Falta dinero dinero, el dinero es dinero...");


    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void tf_ingresoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tf_ingresoPropertyChange

    }//GEN-LAST:event_tf_ingresoPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_bitCoin;
    private javax.swing.JButton btn_efectivo;
    private javax.swing.JComboBox<String> cbx_clientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lbl_cambio;
    private javax.swing.JTextField tf_ingreso;
    // End of variables declaration//GEN-END:variables

    private void llenarCBX() {
        Conector con = new Conector();
        ClienteDAO dame_bd = new ClienteDAO(con.conectarMySQL());
        ArrayList<ClienteVO> clientes = dame_bd.consultaMasiva();
        
        for (ClienteVO c : clientes) {
            cbx_clientes.addItem(c.getNombre_cliente());
        }
    }
}
